apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-gateway
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
    - name: test
      port: 5672
      targetPort: 5672
    - name: test2
      port: 15672
      targetPort: 15672


