server:
  port: 9092

logging:
  level:
    com.muhammet: DEBUG
    org.springframework: DEBUG
  file:
    name: user-service-application.log
    max-size: 1MB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: muhammet
    password: Aa123456*
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: user-service
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: 34.70.190.164
      port: 19589
      database: bilgeyarisma
      username: bilgeadamuser
      password: "C[?K-6)pDZe]ju`-ROi%|or8C!G1ll"

raceapplication:
  url:
    auth: http://localhost:9090/auth-service/
    main: http://localhost:9091/main-service/
    user: http://localhost:9092/user-service/
