server:
  port: 9092

logging:
  level:
    root: WARN
    org.muhammet: DEBUG
    org.springframework: INFO
  file:
    name: user-service-application.log
    max-size: 1MB

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: 'jdbc:postgresql://localhost:5432/YarismaDB'
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/auth-service/
    main: http://localhost:9091/main-service/
    user: http://localhost:9092/user-service/
